"""gRPC client for Overwatch voice server."""
import logging
from typing import Optional
import grpc

_LOGGER = logging.getLogger(__name__)

# Import generated proto files
# These are generated by running: python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. voice.proto
try:
    from .proto import voice_pb2, voice_pb2_grpc
except ImportError:
    _LOGGER.error(
        "Proto files not generated. Run 'python3 -m grpc_tools.protoc -I. --python_out=. "
        "--grpc_python_out=. voice.proto' in the proto directory."
    )
    raise


class OverwatchClient:
    """Client for communicating with Overwatch voice server via gRPC."""

    def __init__(self, host: str, port: int = 50051):
        """Initialize the client.

        Args:
            host: Host address of the voice server
            port: Port number (default: 50051)
        """
        self.host = host
        self.port = port
        self.address = f"{host}:{port}"
        self._channel = None
        self._stub = None

    def connect(self):
        """Create gRPC channel and stub."""
        try:
            self._channel = grpc.insecure_channel(self.address)
            self._stub = voice_pb2_grpc.VoiceServiceStub(self._channel)
            _LOGGER.info(f"Connected to voice server at {self.address}")
            return True
        except Exception as e:
            _LOGGER.error(f"Failed to connect to {self.address}: {e}")
            return False

    def disconnect(self):
        """Close the gRPC channel."""
        if self._channel:
            self._channel.close()
            self._channel = None
            self._stub = None
            _LOGGER.info("Disconnected from voice server")

    def set_alarm(
        self,
        alarm_id: str,
        enabled: bool,
        volume: Optional[float] = None
    ) -> tuple[bool, str]:
        """Enable or disable an alarm.

        Args:
            alarm_id: ID of the alarm to control
            enabled: True to start the alarm, False to stop it
            volume: Optional volume level (0.0-1.0)

        Returns:
            Tuple of (success: bool, message: str)
        """
        if not self._stub:
            if not self.connect():
                return False, "Failed to connect to voice server"

        try:
            request = voice_pb2.SetAlarmRequest(
                alarm_id=alarm_id,
                enabled=enabled
            )

            if volume is not None:
                request.volume = volume

            response = self._stub.SetAlarm(request, timeout=10.0)
            _LOGGER.debug(
                f"SetAlarm response: success={response.success}, message={response.message}"
            )
            return response.success, response.message

        except grpc.RpcError as e:
            _LOGGER.error(f"gRPC error in set_alarm: {e.code()} - {e.details()}")
            return False, f"RPC error: {e.details()}"
        except Exception as e:
            _LOGGER.error(f"Error in set_alarm: {e}")
            return False, str(e)

    def verbalise(
        self,
        text: str,
        notification_tone_id: Optional[str] = None,
        voice_id: Optional[str] = None,
        volume: Optional[float] = None
    ) -> tuple[bool, str]:
        """Synthesize and play text as speech.

        Args:
            text: Text to speak
            notification_tone_id: Optional notification tone to play before speech
            voice_id: Optional voice ID (e.g., "Amy", "Joanna")
            volume: Optional volume level (0.0-1.0)

        Returns:
            Tuple of (success: bool, message: str)
        """
        if not self._stub:
            if not self.connect():
                return False, "Failed to connect to voice server"

        try:
            request = voice_pb2.VerbaliseRequest(text=text)

            if notification_tone_id is not None:
                request.notification_tone_id = notification_tone_id
            if voice_id is not None:
                request.voice_id = voice_id
            if volume is not None:
                request.volume = volume

            response = self._stub.Verbalise(request, timeout=30.0)
            _LOGGER.debug(
                f"Verbalise response: success={response.success}, message={response.message}"
            )
            return response.success, response.message

        except grpc.RpcError as e:
            _LOGGER.error(f"gRPC error in verbalise: {e.code()} - {e.details()}")
            return False, f"RPC error: {e.details()}"
        except Exception as e:
            _LOGGER.error(f"Error in verbalise: {e}")
            return False, str(e)

    def __enter__(self):
        """Context manager entry."""
        self.connect()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.disconnect()
