# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\x05voice\"T\n\x0fSetAlarmRequest\x12\x10\n\x08\x61larm_id\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x13\n\x06volume\x18\x03 \x01(\x02H\x00\x88\x01\x01\x42\t\n\x07_volume\"4\n\x10SetAlarmResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xa0\x01\n\x10VerbaliseRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12!\n\x14notification_tone_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08voice_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06volume\x18\x04 \x01(\x02H\x02\x88\x01\x01\x42\x17\n\x15_notification_tone_idB\x0b\n\t_voice_idB\t\n\x07_volume\"5\n\x11VerbaliseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x01\n\x0cVoiceService\x12;\n\x08SetAlarm\x12\x16.voice.SetAlarmRequest\x1a\x17.voice.SetAlarmResponse\x12>\n\tVerbalise\x12\x17.voice.VerbaliseRequest\x1a\x18.voice.VerbaliseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETALARMREQUEST']._serialized_start=22
  _globals['_SETALARMREQUEST']._serialized_end=106
  _globals['_SETALARMRESPONSE']._serialized_start=108
  _globals['_SETALARMRESPONSE']._serialized_end=160
  _globals['_VERBALISEREQUEST']._serialized_start=163
  _globals['_VERBALISEREQUEST']._serialized_end=323
  _globals['_VERBALISERESPONSE']._serialized_start=325
  _globals['_VERBALISERESPONSE']._serialized_end=378
  _globals['_VOICESERVICE']._serialized_start=381
  _globals['_VOICESERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
