# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voice_pb2 as voice__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetAlarm = channel.unary_unary(
                '/voice.VoiceService/SetAlarm',
                request_serializer=voice__pb2.SetAlarmRequest.SerializeToString,
                response_deserializer=voice__pb2.SetAlarmResponse.FromString,
                _registered_method=True)
        self.Verbalise = channel.unary_unary(
                '/voice.VoiceService/Verbalise',
                request_serializer=voice__pb2.VerbaliseRequest.SerializeToString,
                response_deserializer=voice__pb2.VerbaliseResponse.FromString,
                _registered_method=True)


class VoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetAlarm(self, request, context):
        """Enable or disable an alarm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verbalise(self, request, context):
        """Synthesise and play a text prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAlarm,
                    request_deserializer=voice__pb2.SetAlarmRequest.FromString,
                    response_serializer=voice__pb2.SetAlarmResponse.SerializeToString,
            ),
            'Verbalise': grpc.unary_unary_rpc_method_handler(
                    servicer.Verbalise,
                    request_deserializer=voice__pb2.VerbaliseRequest.FromString,
                    response_serializer=voice__pb2.VerbaliseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice.VoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice.VoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice.VoiceService/SetAlarm',
            voice__pb2.SetAlarmRequest.SerializeToString,
            voice__pb2.SetAlarmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verbalise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice.VoiceService/Verbalise',
            voice__pb2.VerbaliseRequest.SerializeToString,
            voice__pb2.VerbaliseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
